### PR TITLE
Responsive features to make things easier on mobile

### PR DESCRIPTION
**Pull request by Stuffbutts**
# Features added
* New table format when on a small screened device (max 768px)
* Collapse buttons for panel headers on small device
* Auto collapse input on import
* some new classes
* Bootstrap grid system
* Reorganized CSS

I tried to change as little of the original code as possible and only added html elements, classes, and IDs where needed or logical. I used SCSS and breakpoint to generate the css, but did not include it to keep everything nice an light. I can include it if you would like.

*I have done testing and by all my tests everything works perfectly fine. If you find issues, I'll be happy to look at and fix them.*

If there is something you aren't a fan of, let's talk about it and I'm sure we can make it work **even better!**

### CODE REVIEW

**Comment by tomcur** [comment]
Thank you for the enhancements! I'll review them soon. Please also include the original SCSS file.

**Comment by Stuffbutts** [comment]
I will add the scss file, the config.rb for compass compilation, the bower.json for the breakpoint-sass component, and the .gitignore for you later tonight (around **5:30PM EST**)! Thanks!

**Comment by Stuffbutts** [comment]
I decided that the bower_components portion was unnecessary and took some time doing a few quick fixes in the style.scss for media queries.

**Comment by tomcur** [comment]
Merged! Thank you for the improvements. How can I credit you in the on-site changelog?

**Comment by Stuffbutts** [comment]
Linking to my github user page would be fine with me :) https://github.com/Stuffbutts

**Comment by tomcur** [comment]
Thank you! The improvements are now live.

**Pull request merged**
